name: Veracode Security Scan

on: 
  pull_request:
    branches:
      - Fedramp
      - main
  #schedule:
  #  - cron: 0 4 * * *
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Veracode SCA scan
